# Stage 1: Development
FROM node:12-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# Run Angular in live-reload mode
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
